version: "3.8"

services:
  angular:
    build:
      context: .
      dockerfile: apps/frontend-angular/Dockerfile
    tty: true
    stdin_open: true
    tmpfs:
      - /tmp # Czysczenie plikow tymczasowych /tmp pomaga rozwiazac problem: https://github.com/nrwl/nx/issues/21610
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - frontend_nx_cache:/app/.angular/
      - frontend_angular_cache:/app/.nx/
      - dist:/app/dist/
    ports:
      - 4200:4200
    restart: on-failure

  api:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    tty: true
    stdin_open: true
    tmpfs:
      - /tmp # Czysczenie plikow tymczasowych /tmp pomaga rozwiazac problem: https://github.com/nrwl/nx/issues/21610
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - backend_nx_cache:/app/.angular/
      - backend_angular_cache:/app/.nx/
      - dist:/app/dist/
    ports:
      - 3000:3000
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  node_modules:
  backend_nx_cache:
  backend_angular_cache:
  frontend_nx_cache:
  frontend_angular_cache:
  dist:
