version: "3.8"

services:
  angular:
    image: gv-cv-prod-angular:latest
    tty: true
    stdin_open: true
    ports:
      - 4000:4000
    environment:
      - SSR_ENABLE_PERFORMANCE_PROFILER=false
      - SSR_ENABLE_BACKEND_PROXY=true
      - SSR_ENABLE_TEST_ENDPOINTS=false
      - BACKEND_API_HOST=http://api:3000

  api:
    image: gv-cv-prod-backend:latest
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    environment:
      - PDF_GENERATOR_HOSTNAME_REPLACE_RULES=localhost=host.docker.internal
      - API_DOC_ENABLED=false
      - GRAPHQL_PLAYGROUND=false
    extra_hosts:
      - "host.docker.internal:host-gateway"
