version: "3.8"

services:
  angular:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - nx_cache:/app/.angular/
      - angular_cache:/app/.nx/

    ports:
      - 4200:4200
    restart: on-failure

  api:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - nx_cache:/app/.angular/
      - angular_cache:/app/.nx/
    ports:
      - 3000:3000
    restart: on-failure

volumes:
  node_modules:
  nx_cache:
  angular_cache:
