version: "3.8"

services:
  angular:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./:/app
    ports:
      - 4200:4200
    command: ["npx", "nx", "serve", "frontend"]
