name: 'CI / CA'
on:
  pull_request:
  workflow_call:
jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Get Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
      - name: Setup NX SHAs
        uses: nrwl/nx-set-shas@v3
      # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track main origin/main
        if: "!contains(github.ref, 'main')"
      - name: Run lint
        run: npx nx affected -t lint --parallel=3

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
      - name: Setup NX SHAs
        uses: nrwl/nx-set-shas@v3
      # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track main origin/main
        if: "!contains(github.ref, 'main')"
      - name: Run tests
        run: npx nx affected -t test --parallel=3

  e2e:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
      - name: Setup NX SHAs
        uses: nrwl/nx-set-shas@v3
      # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track main origin/main
        if: "!contains(github.ref, 'main')"
      - name: Run tests
        id: run-tests
        run: npx nx affected -t e2e --parallel=1 --verbose
      - name: Upload tests reports
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: e2e-tests-report
          path: dist/cypress

