name: 'CI / CA / CD'
on:
  push:
    branches:
      - main
jobs:
  lint-and-test:
    uses: ./.github/workflows/ci-ca.yml

  deploy:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Get Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
      - name: Setup NX SHAs
        uses: nrwl/nx-set-shas@v3
      - run: echo 'DEPLOY HERE :)'
      - run: npx nx show projects --affected --withTarget docker-build-image
      - run: npx nx show projects --affected --withTarget docker-publish-image
#      - name: Deploy to Kubernetes cluster
#        uses: ./.github/actions/deploy
#        with:
#          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
#          K8S_CONFIG: ${{ secrets.K8S_CONFIG }}
