name: '[main branch] Lint & Test & Deploy'
on:
  push:
    branches:
      - main
jobs:
  lint-and-test:
    uses: ./.github/workflows/ci-feature.yml

  deploy:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
      - name: Deploy to Kubernetes cluster
        uses: ./.github/actions/deploy
        with:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          K8S_CONFIG: ${{ secrets.K8S_CONFIG }}
