name: '[main branch] Lint & Test & Deploy'
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Get Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
      - name: Setup NX Shas
        uses: nrwl/nx-set-shas@v3
      # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track main origin/main
      - name: Run lint
        run: npx nx affected -t lint --parallel=3

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
      - name: Setup NX Shas
        uses: nrwl/nx-set-shas@v3
      # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track main origin/main
      - name: Run tests
        run: npx nx run-many -t test --parallel=3

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Load & cache dependencies
        uses: ./.github/actions/cached-deps
      - name: Deploy to Kubernetes cluster
        uses: ./.github/actions/deploy
        with:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          K8S_CONFIG: ${{ secrets.K8S_CONFIG }}
